package ht.ihsi.inventaireterrain.Backend;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ht.ihsi.inventaireterrain.Backend.Personnel;
import ht.ihsi.inventaireterrain.Backend.Inventaire;
import ht.ihsi.inventaireterrain.Backend.Batiment;
import ht.ihsi.inventaireterrain.Backend.Logement;
import ht.ihsi.inventaireterrain.Backend.Departement;
import ht.ihsi.inventaireterrain.Backend.Commune;
import ht.ihsi.inventaireterrain.Backend.Vqse;
import ht.ihsi.inventaireterrain.Backend.CodeSDE;

import ht.ihsi.inventaireterrain.Backend.PersonnelDao;
import ht.ihsi.inventaireterrain.Backend.InventaireDao;
import ht.ihsi.inventaireterrain.Backend.BatimentDao;
import ht.ihsi.inventaireterrain.Backend.LogementDao;
import ht.ihsi.inventaireterrain.Backend.DepartementDao;
import ht.ihsi.inventaireterrain.Backend.CommuneDao;
import ht.ihsi.inventaireterrain.Backend.VqseDao;
import ht.ihsi.inventaireterrain.Backend.CodeSDEDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personnelDaoConfig;
    private final DaoConfig inventaireDaoConfig;
    private final DaoConfig batimentDaoConfig;
    private final DaoConfig logementDaoConfig;
    private final DaoConfig departementDaoConfig;
    private final DaoConfig communeDaoConfig;
    private final DaoConfig vqseDaoConfig;
    private final DaoConfig codeSDEDaoConfig;

    private final PersonnelDao personnelDao;
    private final InventaireDao inventaireDao;
    private final BatimentDao batimentDao;
    private final LogementDao logementDao;
    private final DepartementDao departementDao;
    private final CommuneDao communeDao;
    private final VqseDao vqseDao;
    private final CodeSDEDao codeSDEDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personnelDaoConfig = daoConfigMap.get(PersonnelDao.class).clone();
        personnelDaoConfig.initIdentityScope(type);

        inventaireDaoConfig = daoConfigMap.get(InventaireDao.class).clone();
        inventaireDaoConfig.initIdentityScope(type);

        batimentDaoConfig = daoConfigMap.get(BatimentDao.class).clone();
        batimentDaoConfig.initIdentityScope(type);

        logementDaoConfig = daoConfigMap.get(LogementDao.class).clone();
        logementDaoConfig.initIdentityScope(type);

        departementDaoConfig = daoConfigMap.get(DepartementDao.class).clone();
        departementDaoConfig.initIdentityScope(type);

        communeDaoConfig = daoConfigMap.get(CommuneDao.class).clone();
        communeDaoConfig.initIdentityScope(type);

        vqseDaoConfig = daoConfigMap.get(VqseDao.class).clone();
        vqseDaoConfig.initIdentityScope(type);

        codeSDEDaoConfig = daoConfigMap.get(CodeSDEDao.class).clone();
        codeSDEDaoConfig.initIdentityScope(type);

        personnelDao = new PersonnelDao(personnelDaoConfig, this);
        inventaireDao = new InventaireDao(inventaireDaoConfig, this);
        batimentDao = new BatimentDao(batimentDaoConfig, this);
        logementDao = new LogementDao(logementDaoConfig, this);
        departementDao = new DepartementDao(departementDaoConfig, this);
        communeDao = new CommuneDao(communeDaoConfig, this);
        vqseDao = new VqseDao(vqseDaoConfig, this);
        codeSDEDao = new CodeSDEDao(codeSDEDaoConfig, this);

        registerDao(Personnel.class, personnelDao);
        registerDao(Inventaire.class, inventaireDao);
        registerDao(Batiment.class, batimentDao);
        registerDao(Logement.class, logementDao);
        registerDao(Departement.class, departementDao);
        registerDao(Commune.class, communeDao);
        registerDao(Vqse.class, vqseDao);
        registerDao(CodeSDE.class, codeSDEDao);
    }
    
    public void clear() {
        personnelDaoConfig.getIdentityScope().clear();
        inventaireDaoConfig.getIdentityScope().clear();
        batimentDaoConfig.getIdentityScope().clear();
        logementDaoConfig.getIdentityScope().clear();
        departementDaoConfig.getIdentityScope().clear();
        communeDaoConfig.getIdentityScope().clear();
        vqseDaoConfig.getIdentityScope().clear();
        codeSDEDaoConfig.getIdentityScope().clear();
    }

    public PersonnelDao getPersonnelDao() {
        return personnelDao;
    }

    public InventaireDao getInventaireDao() {
        return inventaireDao;
    }

    public BatimentDao getBatimentDao() {
        return batimentDao;
    }

    public LogementDao getLogementDao() {
        return logementDao;
    }

    public DepartementDao getDepartementDao() {
        return departementDao;
    }

    public CommuneDao getCommuneDao() {
        return communeDao;
    }

    public VqseDao getVqseDao() {
        return vqseDao;
    }

    public CodeSDEDao getCodeSDEDao() {
        return codeSDEDao;
    }

}
