package ht.ihsi.inventaireterrain.Backend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_logement".
 */
public class Logement {

    private Long IdLogement;
    private Long BatimentId;
    private Integer NumeroLogement;
    private String NomCompletChefMenage;
    private String PhoneChefMenage;
    private Integer NbrHommeVivant;
    private Integer NbrFemmeVivant;
    private String Remarques;

    public Logement() {
    }

    public Logement(Long IdLogement) {
        this.IdLogement = IdLogement;
    }

    public Logement(Long IdLogement, Long BatimentId, Integer NumeroLogement, String NomCompletChefMenage, String PhoneChefMenage, Integer NbrHommeVivant, Integer NbrFemmeVivant, String Remarques) {
        this.IdLogement = IdLogement;
        this.BatimentId = BatimentId;
        this.NumeroLogement = NumeroLogement;
        this.NomCompletChefMenage = NomCompletChefMenage;
        this.PhoneChefMenage = PhoneChefMenage;
        this.NbrHommeVivant = NbrHommeVivant;
        this.NbrFemmeVivant = NbrFemmeVivant;
        this.Remarques = Remarques;
    }

    public Long getIdLogement() {
        return IdLogement;
    }

    public void setIdLogement(Long IdLogement) {
        this.IdLogement = IdLogement;
    }

    public Long getBatimentId() {
        return BatimentId;
    }

    public void setBatimentId(Long BatimentId) {
        this.BatimentId = BatimentId;
    }

    public Integer getNumeroLogement() {
        return NumeroLogement;
    }

    public void setNumeroLogement(Integer NumeroLogement) {
        this.NumeroLogement = NumeroLogement;
    }

    public String getNomCompletChefMenage() {
        return NomCompletChefMenage;
    }

    public void setNomCompletChefMenage(String NomCompletChefMenage) {
        this.NomCompletChefMenage = NomCompletChefMenage;
    }

    public String getPhoneChefMenage() {
        return PhoneChefMenage;
    }

    public void setPhoneChefMenage(String PhoneChefMenage) {
        this.PhoneChefMenage = PhoneChefMenage;
    }

    public Integer getNbrHommeVivant() {
        return NbrHommeVivant;
    }

    public void setNbrHommeVivant(Integer NbrHommeVivant) {
        this.NbrHommeVivant = NbrHommeVivant;
    }

    public Integer getNbrFemmeVivant() {
        return NbrFemmeVivant;
    }

    public void setNbrFemmeVivant(Integer NbrFemmeVivant) {
        this.NbrFemmeVivant = NbrFemmeVivant;
    }

    public String getRemarques() {
        return Remarques;
    }

    public void setRemarques(String Remarques) {
        this.Remarques = Remarques;
    }

}
