package ht.ihsi.inventaireterrain.Backend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "tbl_personnel".
 */
public class Personnel {

    private Long persId;
    private String sdeId;
    private String nom;
    private String prenom;
    private String sexe;
    private String nomUtilisateur;
    private String motDePasse;
    private String email;
    private Boolean estActif;
    private Integer ProfileId;

    public Personnel() {
    }

    public Personnel(Long persId) {
        this.persId = persId;
    }

    public Personnel(Long persId, String sdeId, String nom, String prenom, String sexe, String nomUtilisateur, String motDePasse, String email, Boolean estActif, Integer ProfileId) {
        this.persId = persId;
        this.sdeId = sdeId;
        this.nom = nom;
        this.prenom = prenom;
        this.sexe = sexe;
        this.nomUtilisateur = nomUtilisateur;
        this.motDePasse = motDePasse;
        this.email = email;
        this.estActif = estActif;
        this.ProfileId = ProfileId;
    }

    public Long getPersId() {
        return persId;
    }

    public void setPersId(Long persId) {
        this.persId = persId;
    }

    public String getSdeId() {
        return sdeId;
    }

    public void setSdeId(String sdeId) {
        this.sdeId = sdeId;
    }

    public String getNom() {
        return nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getSexe() {
        return sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public String getNomUtilisateur() {
        return nomUtilisateur;
    }

    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }

    public String getMotDePasse() {
        return motDePasse;
    }

    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getEstActif() {
        return estActif;
    }

    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }

    public Integer getProfileId() {
        return ProfileId;
    }

    public void setProfileId(Integer ProfileId) {
        this.ProfileId = ProfileId;
    }

}
